In [1]:
import pandas as pd
import numpy as np
df = pd.read_pickle('./data/Test Player Innings Stats - All Teams.pkl')

In [2]:
df.head()

,playername,runs,mins,batted,notout,ballsfaced,fours,sixes,inningsnumber,opposition,ground,date,country,numoversbowled,oversbowled,maidens,runsconceded,wickets
0,L Hutton,364.0,797.0,True,False,847.0,35.0,0.0,1,v Australia,The Oval,1938/08/20,England,NaN,NaN,NaN,NaN,NaN
1,WR Hammond,336.0,318.0,True,True,NaN,34.0,10.0,2,v New Zealand,Auckland,1933/03/31,England,NaN,NaN,NaN,NaN,NaN
2,GA Gooch,333.0,628.0,True,False,485.0,43.0,3.0,1,v India,Lord's,1990/07/26,England,NaN,NaN,NaN,NaN,NaN
3,A Sandham,325.0,600.0,True,False,640.0,28.0,0.0,1,v West Indies,Kingston,1930/04/03,England,NaN,NaN,NaN,NaN,NaN
4,JH Edrich,310.0,532.0,True,True,450.0,52.0,5.0,1,v New Zealand,Leeds,1965/07/08,England,NaN,NaN,NaN,NaN,NaN

In [7]:
df[(df.batted == False) & (pd.isna(df.runs)) & (pd.isna(num))]

,playername,runs,mins,batted,notout,ballsfaced,fours,sixes,inningsnumber,opposition,ground,date,country,numoversbowled,oversbowled,maidens,runsconceded,wickets
17691,J Southerton,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Melbourne,1877/03/31,England,NaN,NaN,NaN,NaN,NaN
17692,T Armitage,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Melbourne,1877/03/31,England,NaN,NaN,NaN,NaN,NaN
17693,James Lillywhite jnr,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Melbourne,1877/03/31,England,NaN,NaN,NaN,NaN,NaN
17694,F Morley,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,The Oval,1880/09/06,England,NaN,NaN,NaN,NaN,NaN
17695,AG Steel,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,The Oval,1880/09/06,England,NaN,NaN,NaN,NaN,NaN
17696,A Shaw,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,The Oval,1880/09/06,England,NaN,NaN,NaN,NaN,NaN
17697,Lord Harris,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,The Oval,1880/09/06,England,NaN,NaN,NaN,NaN,NaN
17698,T Emmett,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,Melbourne,1882/03/10,England,NaN,NaN,NaN,NaN,NaN
17699,R Pilling,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,Melbourne,1882/03/10,England,NaN,NaN,NaN,NaN,NaN
17700,A Shrewsbury snr,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,Melbourne,1882/03/10,England,NaN,NaN,NaN,NaN,NaN
17701,WE Midwinter,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,Melbourne,1882/03/10,England,NaN,NaN,NaN,NaN,NaN
17702,A Shaw,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,Melbourne,1882/03/10,England,NaN,NaN,NaN,NaN,NaN
17703,E Peate,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,Melbourne,1882/03/10,England,NaN,NaN,NaN,NaN,NaN
17704,WH Scotton,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,Melbourne,1882/03/10,England,NaN,NaN,NaN,NaN,NaN
17705,WW Read,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,The Oval,1884/08/11,England,NaN,NaN,NaN,NaN,NaN
17706,G Ulyett,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,The Oval,1884/08/11,England,NaN,NaN,NaN,NaN,NaN
17707,W Barnes,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,The Oval,1884/08/11,England,NaN,NaN,NaN,NaN,NaN
17708,WH Scotton,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,The Oval,1884/08/11,England,NaN,NaN,NaN,NaN,NaN
17709,WG Grace,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,The Oval,1884/08/11,England,NaN,NaN,NaN,NaN,NaN
17710,AG Steel,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,The Oval,1884/08/11,England,NaN,NaN,NaN,NaN,NaN
17711,E Peate,NaN,NaN,False,False,NaN,NaN,NaN,3,v Australia,The Oval,1884/08/11,England,NaN,NaN,NaN,NaN,NaN
17712,JM Read,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Adelaide,1884/12/12,England,NaN,NaN,NaN,NaN,NaN
17713,J Briggs,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Adelaide,1884/12/12,England,NaN,NaN,NaN,NaN,NaN
17714,J Hunter,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Adelaide,1884/12/12,England,NaN,NaN,NaN,NaN,NaN
17715,G Ulyett,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Adelaide,1884/12/12,England,NaN,NaN,NaN,NaN,NaN
17716,W Bates,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Adelaide,1884/12/12,England,NaN,NaN,NaN,NaN,NaN
17717,W Attewell,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Adelaide,1884/12/12,England,NaN,NaN,NaN,NaN,NaN
17718,R Peel,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Adelaide,1884/12/12,England,NaN,NaN,NaN,NaN,NaN
17719,W Flowers,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Melbourne,1885/01/01,England,NaN,NaN,NaN,NaN,NaN
17720,R Peel,NaN,NaN,False,False,NaN,NaN,NaN,4,v Australia,Melbourne,1885/01/01,England,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188859,KJ O'Brien,NaN,NaN,False,False,NaN,NaN,NaN,4,v Pakistan,Dublin (Malahide),2018/05/11,Ireland,0.0,0.0,NaN,NaN,NaN
188860,GC Wilson,NaN,NaN,False,False,NaN,NaN,NaN,4,v Pakistan,Dublin (Malahide),2018/05/11,Ireland,0.0,0.0,NaN,NaN,NaN
188861,WTS Porterfield,NaN,NaN,False,False,NaN,NaN,NaN,4,v Pakistan,Dublin (Malahide),2018/05/11,Ireland,0.0,0.0,NaN,NaN,NaN
188862,A Balbirnie,NaN,NaN,False,False,NaN,NaN,NaN,4,v Pakistan,Dublin (Malahide),2018/05/11,Ireland,0.0,0.0,NaN,NaN,NaN
188863,PR Stirling,NaN,NaN,False,False,NaN,NaN,NaN,4,v Pakistan,Dublin (Malahide),2018/05/11,Ireland,0.0,0.0,NaN,NaN,NaN
188864,EC Joyce,NaN,NaN,False,False,NaN,NaN,NaN,4,v Pakistan,Dublin (Malahide),2018/05/11,Ireland,0.0,0.0,NaN,NaN,NaN
188865,NJ O'Brien,NaN,NaN,False,False,NaN,NaN,NaN,4,v Pakistan,Dublin (Malahide),2018/05/11,Ireland,0.0,0.0,NaN,NaN,NaN
188866,WTS Porterfield,NaN,NaN,False,False,NaN,NaN,NaN,2,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188867,A Balbirnie,NaN,NaN,False,False,NaN,NaN,NaN,2,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188868,PR Stirling,NaN,NaN,False,False,NaN,NaN,NaN,2,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188869,SW Poynter,NaN,NaN,False,False,NaN,NaN,NaN,2,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188870,JA McCollum,NaN,NaN,False,False,NaN,NaN,NaN,2,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188871,KJ O'Brien,NaN,NaN,False,False,NaN,NaN,NaN,4,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188872,WTS Porterfield,NaN,NaN,False,False,NaN,NaN,NaN,4,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188873,WTS Porterfield,NaN,NaN,False,False,NaN,NaN,NaN,4,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188874,PR Stirling,NaN,NaN,False,False,NaN,NaN,NaN,4,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188875,SW Poynter,NaN,NaN,False,False,NaN,NaN,NaN,4,v Afghanistan,Dehradun,2019/03/15,Ireland,0.0,0.0,NaN,NaN,NaN
188876,KJ O'Brien,NaN,NaN,False,False,NaN,NaN,NaN,1,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188877,GC Wilson,NaN,NaN,False,False,NaN,NaN,NaN,1,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188878,WTS Porterfield,NaN,NaN,False,False,NaN,NaN,NaN,1,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188879,A Balbirnie,NaN,NaN,False,False,NaN,NaN,NaN,1,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188880,PR Stirling,NaN,NaN,False,False,NaN,NaN,NaN,1,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188881,AR McBrine,NaN,NaN,False,False,NaN,NaN,NaN,1,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188882,JA McCollum,NaN,NaN,False,False,NaN,NaN,NaN,1,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188883,KJ O'Brien,NaN,NaN,False,False,NaN,NaN,NaN,3,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188884,GC Wilson,NaN,NaN,False,False,NaN,NaN,NaN,3,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188885,WTS Porterfield,NaN,NaN,False,False,NaN,NaN,NaN,3,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188886,A Balbirnie,NaN,NaN,False,False,NaN,NaN,NaN,3,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188887,PR Stirling,NaN,NaN,False,False,NaN,NaN,NaN,3,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN
188888,JA McCollum,NaN,NaN,False,False,NaN,NaN,NaN,3,v England,Lord's,2019/07/24,Ireland,0.0,0.0,NaN,NaN,NaN

In [8]:
df.loc[17691]

playername        J Southerton
runs                       nan
mins                       nan
batted                   False
notout                   False
ballsfaced                 nan
fours                      nan
sixes                      nan
inningsnumber                4
opposition         v Australia
ground               Melbourne
date                1877/03/31
country                England
numoversbowled             nan
oversbowled                nan
maidens                    nan
runsconceded               nan
wickets                    nan
Name: 17691, dtype: object